# expected body substrings for registrations (from MP comments, verified manually)
T = {
('CompPilotConsole','StartChoosingDestination_NewTemp',4):'CameraJumper.TryJump(parent',
('CompPilotConsole','StartChoosingDestination_NewTemp',5):'DestroyTreesAroundSubstructure',
('Building_TurretGun','GetGizmos',0):'ExtractShell',
('Building_TurretGun','GetGizmos',1):'ResetForcedTarget(); SoundDefOf',
('Building_TurretGun','GetGizmos',2):'holdFire = !holdFire',
('SocialCardUtility','DrawPawnRoleSelection',0):'GetRitualBeginWindow',
('SocialCardUtility','DrawPawnRoleSelection',3):'GetRitualBeginWindow',
('CompGlower','CompGetGizmosExtra',2):'try {',
('CompGlower','CompGetGizmosExtra',3):'darklight',
('ITab_Pawn_Visitor','DoPrisonerTab',5):'ideoForConversion = newIdeo',
('Dialog_StyleSelection','DoWindowContents',0):'selectedStyleCategories.Remove',
('Dialog_StyleSelection','DoWindowContents',1):'selectedStyleCategories.Replace',
('Dialog_CreateXenogerm','DrawGenepack',8):'GetGeneBankHoldingPack',
('CompBiosculpterPod','CompGetGizmosExtra',1):'EjectContents(interrupted',
('CompBiosculpterPod','CompGetGizmosExtra',3):'autoLoadNutrition = !',
('CompBiosculpterPod','CompGetGizmosExtra',5):'autoAgeReversal = !',
('CompBiosculpterPod','CompGetGizmosExtra',6):'currentCycleTicksRemaining = 10f',
('CompBiosculpterPod','CompGetGizmosExtra',7):'-= 60000f',
('CompBiosculpterPod','CompGetGizmosExtra',8):'biotunedCountdownTicks = 10',
('CompBiosculpterPod','CompGetGizmosExtra',9):'liquifiedNutrition = 5f',
('MechanitorUtility','GetMechGizmos',2):'SetFaction(Faction.OfPlayer)',
('MechanitorUtility','GetMechGizmos',3):'mech.Kill',
('HumanEmbryo','GetGizmos',2):'ImplantPawnValid(cancel: true)',
('HumanOvum','GetGizmos',1):'EndCurrentJob',
('Building_GrowthVat','GetGizmos',1):'Finish(); innerContainer.TryDropAll',
('Building_GrowthVat','GetGizmos',3):'3600000',
('Building_GrowthVat','GetGizmos',4):'startTick - 60000',
('Building_GrowthVat','GetGizmos',5):'startTick = Find.TickManager.TicksGame; Finish',
('Building_GrowthVat','GetGizmos',6):'DestroyEmbryo',
('Building_GrowthVat','GetGizmos',11):'containedNutrition = 10f',
('Building_GrowthVat','GetGizmos',12):'containedNutrition = 0f',
('PitGate','GetGizmos',3):'lastIncidentTick = -999999',
('Pawn_PlayerSettings','GetGizmos',1):'animalsReleased = !',
('Pawn_PlayerSettings','GetGizmos',2):'InHorDistOf',
('CompBandNode','CompGetGizmosExtra',7):'TuneTo(localPawn)',
('CompBandNode','CompGetGizmosExtra',8):'tuningTimeLeft = 0',
('CompStudiable','CompGetGizmosExtra',1):'SetStudyEnabled(!',
('CompStudiable','CompGetGizmosExtra',2):'lastStudiedTick',
('CompStudiable','CompGetGizmosExtra',3):'while (!Completed',
('CompHackable','CompGetGizmosExtra',1):'autohack = !autohack',
('CompHackable','CompGetGizmosExtra',7):'defence * 0.1f',
('CompHackable','CompGetGizmosExtra',8):'HackNow()',
('Caravan','GetGizmos',4):'lastLaunchTick',
('Caravan','GetGizmos',16):'base.Tile = pather.Destination',
('Caravan','GetGizmos',12):'!x.Downed).TryRandomElement',
('WorldObject','GetGizmos',1):'LongEventHandler.QueueLongEvent',
('Building_GeneExtractor','GetGizmos',2):'innerContainer.TryDropAll',
('Building_SubcoreScanner','GetGizmos',1):'initScanner = true',
('Building_SubcoreScanner','GetGizmos',6):'fabricationTicksLeft = 0',  # MP comment label is swapped
('Building_SubcoreScanner','GetGizmos',7):'debugDisableNeedForIngredients',  # MP comment label is swapped
('CompMechCarrier','CompGetGizmosExtra',2):'cooldownTicksRemaining = 0',  # MP comment label is swapped
('CompMechCarrier','CompGetGizmosExtra',3):'while (IngredientCount',  # MP comment label is swapped
('CompMechCarrier','CompGetGizmosExtra',4):'ClearAndDestroyContents',  # MP comment label is swapped
('CompAtomizer','CompGetGizmosExtra',1):'autoLoad = !autoLoad',
('CompAtomizer','CompGetGizmosExtra',3):'ticksAtomized = TicksPerAtomize - ticks',
('CompGenepackContainer','CompGetGizmosExtra',1):'ClearAndDestroyContents(); for',
('Gene_Deathrest','GetGizmos',2):'autoWake = !autoWake',
('Gene_Deathrest','GetGizmos',3):'deathrestTicks = MinDeathrestTicks',
('Gene_Deathrest','GetGizmos',5):'OffsetCapacity(newCap',
('Plant','GetGizmos',0):'ThingsInGroup',
('Plant','GetGizmos',1):'TryReproduceNow',
('Hediff_MetalhorrorImplant','GetGizmos',3):'ageTicks = 62500',
('Hediff_MetalhorrorImplant','GetGizmos',6):'DebugSetBiosignature',
('Building_VoidMonolith','GetFloatMenuOptions',0):'InvestigateMonolith',
('CompInteractable','CompGetGizmosExtra',1):'cooldownTicks = 0',
('Building_Door','GetGizmos',1):'holdOpenInt = !',
('CompRefuelable','CompGetGizmosExtra',1):'allowAutoRefuel = !',
('Zone_Growing','GetGizmos',3):'allowCut = !',
('Command_SetTargetFuelLevel','ProcessInput',2):'TargetFuelLevel = value',
('DebugToolsPawns','Options_SetPrimary',3):'equipment.Primary != null',
('ITab_Pawn_Visitor','DoSlaveTab',6):'slaveInteractionMode = currentSlaveIteractionMode',
('Dialog_BeginRitual','DrawRoleSelection',4):'newRole.Assign',
}
T[('Dialog_BeginRitual','DrawRoleSelection',3)]='confirmTextLocal'
